### ISSUE TITLE
0.68 doesn't start

### ISSUE THREAD

**Issue by bmpalmeida** [mbs38/spicierModbus2mqtt#26]
Hello,

Sorry to go again, just to try to help the good project.

0.68 looks like its not running, i installed by hand asyncio which was not in the dependencies, but it doesn't start.

pi@homebridge:/etc/systemd/system $ modbus2mqtt --tcp 192.168.50.142 --config /etc/modbus2mqtt/zantia.csv --mqtt-host localhost --always-publish --verbosity 4
<coroutine object main at 0xf693be28>
sys:1: RuntimeWarning: coroutine 'main' was never awaited
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
pi@homebridge:/etc/systemd/system $

**Comment by mbs38** [comment]
Should be fine now 3f7019e92dc9ee58ca9ca00e1d971647bdf33406
